version: '3.8'

services:
  app:
    build: .
    image: localhost/app:latest
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
      REDIS_HOST: redis
    volumes:
      - .:/app

  mysql:
    image: docker.io/library/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    volumes:
      - todo-mysql-data:/var/lib/mysql

  redis:
    image: docker.io/library/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  todo-mysql-data:
  redis-data:
