name: CI/CD for Podman on Localhost

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install podman and podman-compose
        run: |
          sudo apt-get update
          sudo apt-get -y install podman python3-pip
          pip3 install podman-compose
          echo 'export PATH=$PATH:~/.local/bin' >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          cd $GITHUB_WORKSPACE
          podman build -t localhost/todo-list-app:latest .

      - name: Deploy to localhost
        run: |
          export PATH=$PATH:~/.local/bin
          cd $GITHUB_WORKSPACE
          # Ensure the old containers are stopped and removed
          podman-compose down --remove-orphans || true
          # Bring up the services with the latest image
          podman-compose up -d
