name: Podman CI/CD for To Do List App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: yarn install
      
    - name: Set up Podman
      run: |
        sudo apt-get update
        sudo apt-get -y install podman
        podman --version
        
    - name: Build the Podman image
      run: |
        podman build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/todo-list-app:${GITHUB_SHA::7}
        podman tag ${{ secrets.DOCKER_USERNAME }}/todo-list-app:${GITHUB_SHA::7} ${{ secrets.DOCKER_USERNAME }}/todo-list-app:latest
        
    - name: Run tests
      run: yarn test
        
    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | podman login -u $DOCKER_USERNAME --password-stdin
        
    - name: Push the Podman image
      run: |
        podman push ${{ secrets.DOCKER_USERNAME }}/todo-list-app:${GITHUB_SHA::7}
        podman push ${{ secrets.DOCKER_USERNAME }}/todo-list-app:latest
        
  deploy:
    needs: build_and_test
    runs-on: self-hosted
    
    steps:
    - name: Pull the latest image
      run: |
        podman pull ${{ secrets.DOCKER_USERNAME }}/todo-list-app:latest
        
    - name: Stop and remove existing containers
      run: |
        podman-compose -f /path/to/docker-compose.yml down --remove-orphans
        
    - name: Start the containers
      run: |
        podman-compose -f /path/to/docker-compose.yml up -d
