name: Podman CI/CD for To Do List App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Podman
      run: |
        sudo apt-get update
        sudo apt-get -y install podman
        podman --version
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push images
      run: |
        podman compose build
        podman compose push
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          # Cập nhật hệ thống và cài đặt Podman
          sudo apt-get update
          sudo apt-get install -y podman
          
          # Tạo thư mục dự án nếu chưa tồn tại
          mkdir -p /home/ubuntu/project
          cd /home/ubuntu/project
          
          # Tạo file podman-compose.yml
          cat > podman-compose.yml <<EOF
          version: '3.8'
          services:
            app:
              image: docker.io/${{ secrets.DOCKER_USERNAME }}/todo-list-app:latest
              ports:
                - "3000:3000"
              environment:
                MYSQL_HOST: mysql
                MYSQL_USER: root
                MYSQL_PASSWORD: secret
                MYSQL_DB: todos
                REDIS_HOST: redis
            mysql:
              image: docker.io/${{ secrets.DOCKER_USERNAME }}/todo-list-mysql:latest
              environment:
                MYSQL_ROOT_PASSWORD: secret
                MYSQL_DATABASE: todos
              volumes:
                - todo-mysql-data:/var/lib/mysql
            redis:
              image: docker.io/${{ secrets.DOCKER_USERNAME }}/todo-list-redis:latest
              ports:
                - "6379:6379"
              volumes:
                - redis-data:/data
                
          volumes:
            todo-mysql-data:
            redis-data:
          EOF
          
          # Kéo các image mới nhất
          podman compose pull
          
          # Chạy các container
          podman compose down
          podman compose up -d
