name: Podman CI/CD for To Do List App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman
          podman --version

      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | podman login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build images
        run: |
          podman build -t docker.io/${{ secrets.DOCKER_USERNAME }}/todo-list-app:latest -f Dockerfile .
          podman pull docker.io/library/mysql:8.0
          podman pull docker.io/library/redis:latest

      - name: Push images
        run: |
          podman push docker.io/${{ secrets.DOCKER_USERNAME }}/todo-list-app:latest
          podman tag docker.io/library/mysql:8.0 docker.io/${{ secrets.DOCKER_USERNAME }}/todo-list-mysql:latest
          podman push docker.io/${{ secrets.DOCKER_USERNAME }}/todo-list-mysql:latest
          podman tag docker.io/library/redis:latest docker.io/${{ secrets.DOCKER_USERNAME }}/todo-list-redis:latest
          podman push docker.io/${{ secrets.DOCKER_USERNAME }}/todo-list-redis:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Cập nhật hệ thống và cài đặt Podman
            sudo apt-get update
            sudo apt-get install -y podman

            # Đăng nhập Docker Hub
            podman login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            # Kéo các image mới nhất
            podman pull docker.io/${{ secrets.DOCKER_USERNAME }}/todo-list-app:latest
            podman pull docker.io/${{ secrets.DOCKER_USERNAME }}/todo-list-mysql:latest
            podman pull docker.io/${{ secrets.DOCKER_USERNAME }}/todo-list-redis:latest

            # Dừng và xóa các container cũ
            podman stop app mysql redis || true
            podman rm app mysql redis || true

            # Giải phóng cổng 6379 nếu đang sử dụng
            sudo fuser -k 6379/tcp || true

            # Xóa các volumes cũ nếu có
            podman volume rm todo-mysql-data redis-data || true

            # Tạo các volumes mới
            podman volume create todo-mysql-data
            podman volume create redis-data

            # Khởi động MySQL container
            podman run -d --name mysql \
              -e MYSQL_ROOT_PASSWORD=secret \
              -e MYSQL_DATABASE=todos \
              -v todo-mysql-data:/var/lib/mysql \
              docker.io/${{ secrets.DOCKER_USERNAME }}/todo-list-mysql:latest

            # Khởi động Redis container
            podman run -d --name redis \
              -v redis-data:/data \
              -p 6379:6379 \
              docker.io/${{ secrets.DOCKER_USERNAME }}/todo-list-redis:latest

            # Khởi động ứng dụng chính
            podman run -d --name app \
              -p 3000:3000 \
              --env MYSQL_HOST=mysql \
              --env MYSQL_USER=root \
              --env MYSQL_PASSWORD=secret \
              --env MYSQL_DB=todos \
              --env REDIS_HOST=redis \
              docker.io/${{ secrets.DOCKER_USERNAME }}/todo-list-app:latest
