name: CI/CD for Podman

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files for debugging
        run: |
          echo "Current workspace: $GITHUB_WORKSPACE"
          ls -la $GITHUB_WORKSPACE

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install podman and podman-compose
        run: |
          sudo apt-get update
          sudo apt-get -y install podman python3-pip
          pip3 install podman-compose
          echo 'export PATH=$PATH:~/.local/bin' >> $GITHUB_ENV

      - name: Run podman-compose
        run: |
          cd $GITHUB_WORKSPACE
          # Ensure the old containers are stopped and removed
          podman-compose down --remove-orphans
          # Pull the latest image
          podman pull ***/todo-list-app:latest
          # Bring up the services with the latest image
          podman-compose up -d
